sudo: required
service:
 - docker
before_install:
  - docker build -t sreekanthkurapati/partha .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push sreekanthkurapati/partha
notifications:
 email:
   recipients:
     - sreekanthkurapati@gmail.com
   on_success: always
   on_failure: always
